### PR TITLE
Fixes for autotools configuration

### PR DESCRIPTION
**Pull request by vijaysm**
- Remove Fortran dependency completely for all packages (BLAS/LAPACK/HDF5/NetCDF)
- Fix a minor issue with installation

### CODE REVIEW

**Comment by paullric** [comment]
Fails on Cori with:

checking for library containing nc_inq_libvers... -lnetcdf
checking netcdfcpp.h usability... no
checking netcdfcpp.h presence... no
checking for netcdfcpp.h... no
checking for netCDF C++ library... no
configure: error: cannot find NetCDF C++ library

Cori doesn't provide the legacy NetCDF C++ library either "libnetcdfc++.a", so I've been building it myself.  Is there a way to point it at the right directory for this library?

**Comment by vijaysm** [comment]
Do you have an installation of your Netcdf locally ? You can always say
`--with-netcdf=$PATH_TO_MY_NETCDF_INSTALL`. If it has both libnetcdf.* and
libnetcdf_c++.*, configuration will be happy.

Btw, `./configure --help` will show you all available configuration options.

**Comment by paullric** [comment]
The problem is that libnetcdf.* and libnetcdf_c++.* are in different directories.

**Comment by vijaysm** [comment]
I see. I usually install those in the same directory. I can add another configuration option `--with-netcdf-cxx`, where you can specify the Netcdf C++ lib installation path separately, in case if its different from NETCDF_DIR. That should be easy to do.

On a related note, I actually verified on Cori that it works. I had to install my own Netcdf from scratch but linkage was fine. My command was simply:
`../configure CC=cc CXX=CC --with-netcdf=/global/homes/v/vijaysm/install/netcdf --enable-static --disable-shared`

**Comment by paullric** [comment]
The NERSC folks recommended the cray-netcdf module which works, but doesn't include the legacy C++ library (bothersome).  Hence the need to build it separately.

~ Paul

**Pull request merged**
