### PR TITLE
Monotone holes

### PR DESCRIPTION
**Pull request by dmarsico1**
The bilinear and generalized barycentric coordinate schemes that work for meshes with holes.

### CODE REVIEW

**Comment by dmarsico1** [comment]
I just realized that I need to fix something.  I'll submit a new pull request soon.

**Comment by dmarsico1** [comment]
There's a merge conflict in the functions "LinearRemapBilinear" and "LinearRemapGeneralizedBarycentric," but that's because I had to make significant changes to them so that they'll work for meshes with holes.

**Comment by rljacob** [comment]
Should this be closed in favor of #112 ?

**Comment by dmarsico1** [comment]
Yes, this should closed in favor of PR #112.

**Comment by dmarsico1** [comment]
This was closed in favor of PR #112, where the merge conflict is fixed.

**Pull request closed without merging**
