### PR TITLE
Adding autotools configuration support

### PR DESCRIPTION
**Pull request by vijaysm**
Adding autoconf/automake support for Tempest library configuration. All standard targets work cleanly. Modifications to this system should be trivial to make as necessary.

If there are any other specific requests, do let me know. Verified on OSX and Linux.

### CODE REVIEW

**Comment by vijaysm** [comment]
I updated the base to master; Not sure what I was thinking ;)

**Comment by paullric** [comment]
What is the suggested new command order for build?  autoconf / automake do not work out-of-box on my end.  Probably should've checked before merging.

**Comment by vijaysm** [comment]
The workflow would be something like below.

- autoreconf -fi
- Configure system

- a) For out of source builds (recommended): 
`mkdir build && cd build && ../configure --prefix=MY_INSTALL_DIR --with-hdf5=$HDF5_DIR --with-netcdf=$NETCDF_DIR`
-  b) For in source builds: 
`./configure --prefix=MY_INSTALL_DIR --with-hdf5=$HDF5_DIR --with-netcdf=$NETCDF_DIR`

- make all
- make install

**Comment by paullric** [comment]
Pull request of debatable utility unless it actually works out-of-box, particularly since error messages do not point to an easy resolution.  Results of build instructions below.

`Pauls-MacBook-Pro-7:tempestremap paullric$ autoreconf -fi
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
glibtoolize: copying file 'config/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config'.
glibtoolize: copying file 'config/libtool.m4'
glibtoolize: copying file 'config/ltoptions.m4'
glibtoolize: copying file 'config/ltsugar.m4'
glibtoolize: copying file 'config/ltversion.m4'
glibtoolize: copying file 'config/lt~obsolete.m4'
configure.ac:13: installing 'config/compile'
configure.ac:12: installing 'config/missing'
Makefile.am: installing 'config/depcomp'

Pauls-MacBook-Pro-7:tempestremap paullric$ ./configure --prefix=/Users/paullric/Documents/tempestremap --with-hdf5=$HDF5_DIR --with-netcdf=$NETCDF_DIR
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /opt/local/bin/gsed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking whether make sets $(MAKE)... (cached) yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for gfortran... gfortran
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gfortran option to produce PIC... -fno-common
checking if gfortran PIC flag -fno-common works... yes
checking if gfortran static flag -static works... no
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gfortran option to produce PIC... -fno-common
checking if gfortran PIC flag -fno-common works... yes
checking if gfortran static flag -static works... no
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking how to get verbose linking output from gfortran... -v
checking for Fortran libraries of gfortran...  -L/usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0 -L/usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0/../../.. -lgfortran -lquadmath -lm
checking for sgemm_... no
checking for ATL_xerbla in -latlas... no
checking for sgemm_ in -lblas... yes
checking for dgemm_ in -ldgemm... no
checking for sgemm_ in -lmkl... no
checking for sgemm_... (cached) no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) yes
checking for sgemm_ in -lessl... no
checking for sgemm_ in -lblas... (cached) yes
checking how to get verbose linking output from gfortran... -v
checking for Fortran 77 libraries of gfortran...  -L/usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0 -L/usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0/../../.. -lgfortran -lquadmath -lm
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
checking for cheev_... no
checking for cheev_ in -llapack... yes
checking for hdf5... 
checking for H5open in -lhdf5... no
checking for H5Dclose in -lhdf5_hl... no
configure: C++ not checked for yet
checking for netcdf... 
checking for library containing nc_inq_libvers... no
configure: error: cannot find netCDF C library
`

**Comment by vijaysm** [comment]
@paullric HDF5_DIR and NETCDF_DIR point to your HDF5 and NetCDF installations. If you are using Ubuntu installed dependencies, typically, these would be HDF5_DIR=/usr. Else, they point to wherever else you installed HDF5/NetCDF.

**Comment by vijaysm** [comment]
For example, my local out-of-source configuration command looks like this:

`../configure --with-netcdf=/usr/software/netcdf-4.3.0 --with-hdf5=/usr/software/hdf5-1.8.11 --prefix=/usr/software/tempestremap`

Note that this is specific to my system. Depending on your settings, you should update the paths.

**Comment by paullric** [comment]
Ah.  From examining the commit I was under the impression it was automatically performing a search for NetCDF and HDF5.

UCAR/Yellowstone with intel/15.0.3 compiler fails with message:

checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... no
checking whether g++ supports C++11 features with -std=gnu++0x... no
configure: error: *** A compiler with support for C++11 language features is required.

This failure seems to be a common "feature" of the intel compilers on this system, even though it does have limited support for C++11.

**Comment by vijaysm** [comment]
> Ah. From examining the commit I was under the impression it was automatically performing a search for NetCDF and HDF5.

Nope. The configuration system makes no assumption about where things are installed. I think BLAS/LAPACK may be the only ones that are deciphered automatically, depending on whether you are on Ubuntu/OSX. But you could also override those with paths using --with-blas=$BLAS_DIR and --with-lapack=$LAPACK_DIR.

> configure: error: *** A compiler with support for C++11 language features is required.

I'll check on Intel locally and see how to fix this. Should be simple enough. My tests were with GNU/Clang only so far.

**Comment by vijaysm** [comment]
@paullric Can you try explicitly specifying the compilers. I am curious why it say "g++" and not "icpc". You can override the compilers with something like this:

`./configure CC=icc CXX=icpc FC=ifort <OTHER_OPTIONS>`

It probably will still fail though. I was able to replicate it with Intel 15.0.0.

**Comment by paullric** [comment]
The previous output was under MacOSX.  The output below is from Yellowstone:

`[ullrich@yslogin2 tempestremap]$ ./configure CC=icc CXX=icpc FC=ifort --prefix=$PWD/bin --with-netcdf=$NETCDF
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... icc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether icc accepts -g... yes
checking for icc option to accept ISO C89... none needed
checking dependency style of icc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by icc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from icc object... ok
checking how to run the C preprocessor... icc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if icc supports -fno-rtti -fno-exceptions... yes
checking for icc option to produce PIC... -fPIC -DPIC
checking if icc PIC flag -fPIC -DPIC works... yes
checking if icc static flag -static works... yes
checking if icc supports -c -o file.o... yes
checking if icc supports -c -o file.o... (cached) yes
checking whether the icc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether we are using the GNU C++ compiler... yes
checking whether icpc accepts -g... yes
checking dependency style of icpc... gcc3
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether icpc accepts -g... (cached) yes
checking dependency style of icpc... (cached) gcc3
checking how to run the C++ preprocessor... icpc -E
checking for ld used by icpc... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the icpc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for icpc option to produce PIC... -fPIC -DPIC
checking if icpc PIC flag -fPIC -DPIC works... yes
checking if icpc static flag -static works... yes
checking if icpc supports -c -o file.o... yes
checking if icpc supports -c -o file.o... (cached) yes
checking whether the icpc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) icc
checking whether we are using the GNU C compiler... (cached) yes
checking whether icc accepts -g... (cached) yes
checking for icc option to accept ISO C89... (cached) none needed
checking dependency style of icc... (cached) gcc3
checking whether make sets $(MAKE)... (cached) yes
checking whether icpc supports C++11 features by default... no
checking whether icpc supports C++11 features with -std=gnu++11... no
checking whether icpc supports C++11 features with -std=gnu++0x... no
configure: error: *** A compiler with support for C++11 language features is required.`

**Pull request merged**
